version: '3'

services:
  nginx:
    container_name: cms_nginx
    build:
      context: ./docker/nginx/
    ports:
      - 80:80
    volumes:
      - ./src/:/var/www/vhosts/cms/:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      - ./docker/nginx/location.conf:/etc/nginx/conf.d/lib/location.conf:cached
#      - ./log/nginx:/var/log/nginx/:cached
    depends_on:
      - php

  php:
    container_name: cms_php
    build:
      context: ./docker/php/
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./src/:/var/www/vhosts/cms/:cached
      - ./docker/php/www.conf:/etc/php-fpm.d/www.conf:cached
      # - ./log/php:/var/log/php-fpm:cached

  db:
    image: mysql:8.0
    container_name: cms_db
    hostname: mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
#      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cms
      - MYSQL_USER=cms
      - MYSQL_PASSWORD=devcms
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-time-zone=Asia/Tokyo
    volumes:
      - ./database/config/:/etc/mysql/conf.d/

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: cms_pma
    hostname: phpmyadmin
    depends_on:
      - db
    ports:
      - "9090:80"